---
freebsd_instance:
  image_family: freebsd-12-2

task:
  install_script:
    - pkg install -y emulators/virtualbox-ose
  always:
    system_info_script:
      - whoami
      - id
      - uname -msr
      - sysctl kern.osrelease kern.osrevision kern.osreldate
      - sysctl kern.version
      - ifconfig
      - pkg info
      - dmesg
      - ps axd
