---
driver:
  name: vagrant
  customize:
    memory: 2048

transport:
  name: rsync

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 4
  ansible_verbose: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  requirements_path: requirements.yml
  http_proxy: <%= ENV['ANSIBLE_PROXY'] %>
  idempotency_test: true
  additional_copy_path:
    - extra_modules
    - filter_plugins
  # XXX set role_name in cirrus ci to fix up the role name.
  #
  # in cirrus ci, the directory name of PWD is not the repository name, but
  # `cirrus-ci-build`. kitchen copy the role under `roles` directory with that
  # name. thus, ansible cannot  find the role.
  role_name: <%= ENV["CIRRUS_REPO_NAME"] ? ENV["CIRRUS_REPO_NAME"] : "ansible-role-opendistroforelasticsearch" %>

platforms:
  - name: freebsd-12.1-amd64
    driver:
      box: trombik/ansible-freebsd-12.1-amd64
      box_check_update: false
    driver_config:
      ssh:
        shell: '/bin/sh'
    provisioner:
      extra_vars:
        ansible_python_interpreter: '/usr/local/bin/python3'

  - name: ubuntu-18.04-amd64
    driver:
      box: trombik/ansible-ubuntu-18.04-amd64
      box_check_update: false

  - name: ubuntu-20.04-amd64
    driver:
      box: trombik/ansible-ubuntu-20.04-amd64
      box_check_update: false

  - name: centos-7.8-amd64
    driver:
      box: trombik/ansible-centos-7.8-x86_64
      box_check_update: false

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/serverspec/default.yml
    verifier:
      name: shell
      command: rspec -c -f d -I tests/serverspec tests/serverspec/default_spec.rb
